version: "3.8"
services:
  zookeeper-1:
    container_name: zookeeper-1
    image: cashalo/zookeeper:2.7.0
    build:
      context: ./zookeeper
    volumes:
    - ./config/zookeeper-1/zookeeper.properties:/kafka/config/zookeeper.properties
    networks:
    - kafka
  kafka-1:
    container_name: kafka-1
    image: cashalo/kafka:2.7.0
    build: 
      context: .
    volumes:
    - ./config/kafka-1/server.properties:/kafka/config/server.properties
    depends_on:
    - zookeeper-1
    networks:
    - kafka
    ports:
     - 9092:9092
  kafka-2:
    container_name: kafka-2
    image: cashalo/kafka:2.7.0
    build: 
      context: .
    volumes:
    - ./config/kafka-2/server.properties:/kafka/config/server.properties
    depends_on:
    - zookeeper-1
    networks:
    - kafka
    ports:
     - 9093:9093
  kafka-3:
    container_name: kafka-3
    image: cashalo/kafka:2.7.0
    build: 
      context: .
    volumes:
    - ./config/kafka-3/server.properties:/kafka/config/server.properties
    depends_on:
    - zookeeper-1
    networks:
    - kafka
    ports:
     - 9094:9094
networks: 
  kafka:
    name: kafka